CLASS cl_apl_ecatt_script_upload DEFINITION PUBLIC CREATE PUBLIC ABSTRACT.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS cl_apl_ecatt_script_upload IMPLEMENTATION.

ENDCLASS.
