CLASS cl_apl_ecatt_script_download DEFINITION PUBLIC INHERITING FROM cl_apl_ecatt_download CREATE PUBLIC ABSTRACT.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS cl_apl_ecatt_script_download IMPLEMENTATION.

ENDCLASS.
