CLASS cl_apl_ecatt_config_upload DEFINITION PUBLIC INHERITING FROM cl_apl_ecatt_upload CREATE PUBLIC ABSTRACT.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS cl_apl_ecatt_config_upload IMPLEMENTATION.

ENDCLASS.
