CLASS cl_apl_ecatt_script_download DEFINITION PUBLIC CREATE PUBLIC ABSTRACT.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS cl_apl_ecatt_script_download IMPLEMENTATION.

ENDCLASS.
