CLASS cl_apl_ecatt_data_upload DEFINITION PUBLIC INHERITING FROM cl_apl_ecatt_upload CREATE PUBLIC ABSTRACT.

  PUBLIC SECTION.
  PROTECTED SECTION.
    DATA ecatt_object TYPE string.
  PRIVATE SECTION.

ENDCLASS.

CLASS cl_apl_ecatt_data_upload IMPLEMENTATION.

ENDCLASS.
