CLASS cl_gui_object DEFINITION PUBLIC.
  PUBLIC SECTION.
    CLASS-DATA javabean TYPE c LENGTH 1 READ-ONLY.
    CLASS-DATA www_active TYPE c LENGTH 1 READ-ONLY.
ENDCLASS.

CLASS cl_gui_object IMPLEMENTATION.

ENDCLASS.