TYPE-POOL icon.

CONSTANTS icon_abap TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_abap_local TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_abc TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_absence TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_action_success TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_activate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_active_inactive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_activity TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_activity_group TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_add_row TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_address TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_administrative_data TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_adopt TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_alarm TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_alert TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_allow TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_alv_variants TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_annotation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_any_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_apple_numbers TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_arrow_left TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_arrow_right TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_attachment TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_availability_display TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_background_job TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ben_current_benefits TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ben_termination TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_binary_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_formula TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_info_cube TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_monitor TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_report TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_scheduler TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_source_sys_r3 TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_virtual_info_provider TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bmp TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bom TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bom_item TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bom_sub_item TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_booking_ok TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_booking_stop TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_breakpoint TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_breakpoint_disable TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_businav_datamodel TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_businav_entity TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_businav_objects TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_businav_value_chain TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_business_area TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_apd_db TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_apd_source TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_apd_target TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_apd_transformation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_convert_unit TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_dtp_active TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_exception_monitor TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_gis TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_info_cube_ina TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_ra_setting_active TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_ra_setting_inactive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bw_time_sap TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_calculation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_cancel TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_change TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_change_number TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_change_text TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_check TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_checkbox TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_checked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_claim TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_class_connection_space TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_client_breakpoint TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_close TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_closed_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_collapse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_collapse_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_color TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_column_left TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_column_right TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_compare TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_complete TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_composite_activitygroup TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_configuration TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_connect TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_content_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_context_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_context_menu TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_controlling_area TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_convert TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_convert_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_copy_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_cost_components TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_create TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_create_copy TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_create_note TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_create_text TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_customer TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_customer_warehouse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_customs TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dangerous_goods TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_data_area_collapse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_data_area_expand TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_database_table TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_database_table_ina TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_date TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_deactivate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_debugger_continue TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_debugger_step_into TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_debugger_step_out TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_debugger_step_over TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_deceased_patient TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_defect TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delete TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delete_row TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delete_template TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delivery_inbound TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delivery_no_confirmation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delivery_proposal TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_deselect_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_detail TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dimension TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_disconnect TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display_more TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display_note TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display_text TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display_tree TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dispo_level TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_doc TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_doc_header_detail TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_document_model_space TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dot TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dropdownlist TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dummy TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_edit_file TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_eff TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_element TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_eml TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_employee TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_enter_more TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_envelope_closed TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_equal TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_equal_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_equal_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_error_protocol TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_eu TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_execute_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_expand TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_expand_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_export TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_extended_search TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_extra TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_failure TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_fast_entry TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_favorites TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_fax TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_field_with_text TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_filter TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_filter_undo TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_finite TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_first_page TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_flight TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_foreign_key TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_foreign_trace TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_generate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_gif TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_gis_pan TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_gis_pie TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_gis_promote TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_graduate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_graphics TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_greater TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_greater_equal_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_greater_equal_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_greater_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_greater_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_green_light TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_header TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_helpassistent_on TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_hierarchy_act TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_hint TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_history TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_hlp TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_hold TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_host TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_hr_position TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_htm TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_htt TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_icon_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_idoc TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_import TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_import_all_requests TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_import_transport_request TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_include_objects TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_incoming_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_incoming_task TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_incomplete TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_incompletion_log TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_increase_decimal TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_information TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_initial TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_insert_row TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_inspection_characteristic TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_inspection_lot TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_inspection_method TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_install_package TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_intensify TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_intensify_critical TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_intensify_undo TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interface TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_intermediate_sum TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_exclude_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_exclude_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_include_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_include_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_io_attribute TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_its TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_job_detail TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_jpg TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_last_page TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_layout_control TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_inactive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_yellow TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_legal_reg TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_less_equal_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_less_equal_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_less_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_less_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_light_out TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_link TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_linked_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_location TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_locked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_loio_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_lwp TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_mail TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_mapped_relation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_mass_change TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_mass_change_done TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_master_data_act TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_mc_contentindicator TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_critical TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_critical_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_error TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_error_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_information TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_information_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_question TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_question_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_type TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_warning TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_warning_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_model TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_modification_create TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_modification_overview TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_modification_reset TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_modified_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_modify TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_money TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_move TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_msg TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_negative TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_net_graphic TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_next_node TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_next_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_next_page TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_next_value TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_no_status TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_not_equal TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_not_equal_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_not_equal_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_object_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_object_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_office_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_okay TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_class_event TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_class_method TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_connection TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_constant TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_event TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_inst_event TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_interface TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_oo_overwrite TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_open TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_open_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_operation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_order TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_otf_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_other_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_outgoing_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_outgoing_org_unit TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_overview TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_package_application TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_package_dynamic TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_package_standard TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_packing TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_page_left TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_page_right TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_parameter TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_parameter_result TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_partner TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pattern_exclude_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pattern_exclude_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pattern_include_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pattern_include_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pdf TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pdir_back TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_personal_help TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_phio_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_physical_sample TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_plant TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pm_insert TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pm_order TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pm_press TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_position TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_position_hr TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_positive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ppe_snode TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ppe_vnode TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ppt TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_presence TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_previous_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_previous_page TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_previous_value TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_price TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_price_analysis TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_print TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_print_with_parameters TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_product_group TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_profit_center TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_project TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_proshare TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_protocol TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ps_network_activity TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ps_wbs_element TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_public_files TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_qualify TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_query TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_question TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_radiobutton TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_railway TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ranking TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_rating_minus TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_rating_positive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_read_file TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_reclassification TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_red_light TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_reference_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_refresh TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_reject TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_relation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_relation_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_relationship TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_release TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_remove_from_selection TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_remove_row TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_rename TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_replace TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_report_template TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_resubmission TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_role TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_rtf TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_sap TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_save_as_template TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_scrap TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_search TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_search_next TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_select_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_select_block TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_select_detail TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_selection TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_set_b TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_set_copy_in_a TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_set_copy_in_b TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_set_state TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_set_sum TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_settings TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_short_message TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_show_events TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_show_external_jobs TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_simulate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_skip TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_sort_down TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_sort_up TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_space TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_spool_request TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_stack TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_statistics TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_alert TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_best TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_booked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_critical TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_ok TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_open TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_overview TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_partly_booked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_reverse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_stock TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_store TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_store_location TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_stores TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_storno TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_structure TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_submit TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_sum TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_sum_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_summarize TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_supplier TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_sym_log_server TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_back TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_cancel TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_copy TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_cut TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_end TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_extended_help TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_help TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_local_copy TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_local_paste TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_mark TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_okay TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_paste TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_play TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_possible_entries TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_print TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_redo TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_save TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_shortcut TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_start_recording TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_undo TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_user_menu TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_systems TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_systemtype TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_table_settings TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_target_group TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_tbh TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_tbh_hold TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_te_advance_payment TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_terminated_org_unit TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_test TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_text_act TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_text_field TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_text_ina TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_tif TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_time TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_toggle_display_change TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_tools TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_total_left TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_total_right TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_transfer TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_transfer_structure TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_transfer_structure_ina TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_transport TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_transport_point TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_tree TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_trend_decreasing TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_trend_down TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_trend_rising TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_trend_unchanged TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_trend_up TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unlocked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unpack TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unspecified_four TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unspecified_one TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unspecified_three TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unspecified_two TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_url TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_usergroup TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_value_help TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_variable TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_variants TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_video TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_view_form TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_view_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_view_maximize TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_view_table TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_view_thumbnails TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_viewer_optical_archive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_virtual_loio_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_virtual_phio_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_virtual_relation_class TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_voice_output TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_vsd TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_warehouse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_warning TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_application TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_caption TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_component TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_context TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_controller TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_custom_controller TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_iframe TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_image TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_input_field TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_navigation_link TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_radio_button_empty TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_table TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_tag_library TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_toolbar TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_toolbar_caption TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_tree TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_tree_node TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_view TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_view_area TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wd_view_container TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wf_link TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wf_reserve_workitem TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wf_unlink TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wf_workitem_completed TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wf_workitem_error TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wf_workitem_ol TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wizard TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_workflow TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_workflow_activity TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_workflow_fork TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_workflow_process TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_working_plan TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_workplace TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_wri TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_write_file TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ws_plane TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ws_start_whse_proc_backgr TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ws_truck TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ws_whse_stock TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xls TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xlv TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xml_doc TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xxl TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_yellow_light TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_include_in_selection TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_val_quantity_structure TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_connection_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_availability_check TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_toggle_display TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_patient_smartcard TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_businav_process TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_new_task TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ps_relationship TYPE c LENGTH 4 VALUE ''.