TYPE-POOL icon.

CONSTANTS icon_abap TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_active_inactive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_activity_group TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_administrative_data TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_adopt TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_alert TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_availability_display TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_biw_scheduler TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_bom_item TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_breakpoint TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_cancel TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_change TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_change_text TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_checked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_closed_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_collapse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_collapse_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_color TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_column_left TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_column_right TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_complete TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_content_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_create TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_customer_warehouse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_database_table TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_date TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_debugger_step_into TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delete TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_delete_row TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_deselect_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display_more TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_display_text TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_dropdownlist TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_employee TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_enter_more TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_equal_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_equal_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_eu TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_execute_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_expand TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_expand_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_export TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_fast_entry TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_filter TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_foreign_key TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_generate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_green_light TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_header TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_hint TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_import_all_requests TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_import_transport_request TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_incoming_task TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_incomplete TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_initial TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_insert_row TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_exclude_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_include_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_interval_include_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_inactive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_led_yellow TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_location TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_locked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_critical TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_critical_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_error TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_error_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_information TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_information_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_question TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_warning TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_message_warning_small TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_no_status TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_not_equal_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_not_equal_red TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_object_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_office_document TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_okay TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_open_folder TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_order TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_other_object TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_overview TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_page_left TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_page_right TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pattern_include_green TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_pdir_back TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_physical_sample TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_print TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_protocol TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ps_network_activity TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_public_files TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_query TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_red_light TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_reference_list TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_refresh TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_reject TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_relation TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_relationship TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_release TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_save_as_template TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_select_all TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_select_detail TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_selection TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_set_state TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_simulate TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_stack TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_critical TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_ok TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_status_reverse TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_stock TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_stores TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_submit TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_back TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_extended_help TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_help TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_print TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_redo TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_save TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_system_undo TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_time TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_transfer TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_unlocked TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_viewer_optical_archive TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_workflow_fork TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_ws_whse_stock TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xls TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xml_doc TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_xxl TYPE c LENGTH 4 VALUE ''.
CONSTANTS icon_yellow_light TYPE c LENGTH 4 VALUE ''.
